### ISSUE TITLE
Home Assistant

### ISSUE THREAD

**Issue by Piccar** [rhasspy/rhasspy#176]
Hi there,
I installed rhasspy and Home-assistant both in docker as mentioned on their Websites. Both are Up and running. 
Great so far! 
No I want to connect these but I cant get it to work. 
I entered the Hass Adress like "http://192.168.X.X:8123"
And Checked the API-Token twice.
I insertet "intent:" in the configuration file of Homeassistent and restarted the docker.

I tested that the Hass docker can make an POST call to the Text-To-Speech crawler.
Worked! 
I checked the logs of Hass and there is nothing.
I asked my Raspberry multiple times to tell me the time and it responded with the correct JSON File but nothing here on Hass...
(I hope my raspberry doesn't think Im stupid for asking every secound what time it is right now...)

**Comment by h4de5** [comment]
in home-assistant / configuration.yaml:

```
intent:

intent_script:
  GetTime:
    speech:
      text: It is currently {{ as_timestamp (now()) | timestamp_custom('%M') | regex_replace('^0+', '') }} minutes after {{ as_timestamp (now()) | timestamp_custom('%H') }} o'clock
```

in rhasspy / sentences.ini:

```
[GetTime]:
what is the current time
what time is it
```

don't forget to train your rhasspy - hope this helps.
