### ISSUE TITLE
solution for docker on windows

### ISSUE THREAD

**Issue by siparker** [rhasspy/rhasspy#249]
Hi. My docker is running on a windows host machine so -v /etc/localtime:/etc/localtime:ro will not work for me.

I understand there is no official installation for docker on windows but including Tzdata would mean the dependency on linux filesystem is very minimal.

Or are there other solutions for unning on Non unix like docker installs.

I also considered using Qnap containerstation but again i am unsure how to correctly map the volumes as i am not sure what they are for.
is the timezone required?
is the config folder mounted volume just an empty folder that is populated on installation?

**Comment by Romkabouter** [comment]
I am not sure about the timezone part, but the config is an empty folder yes.

Did you find any solution?

**Comment by Wetzel402** [comment]
I had a server running on Windows Docker.  The biggest problem comes when trying to run Rhasspy on Windows Docker as a standalone unit or satellite since Windows Docker has poor hardware support.  I was unable to get the speakers and microphone to work.  

I am currently running my Rhasspy server in QNAP Container Station with the following docker compose...
```
version: '3.5'

services:
  rhasspy:
    image: "rhasspy/rhasspy:latest"
    container_name: rhasspy
    restart: unless-stopped
    volumes:
      - /share/Container/rhasspy/profiles:/profiles
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 12101:12101
    command: --user-profiles /profiles --profile en
    networks:
      backend:
networks:
  backend:
    name: backend
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/24
          gateway: 10.10.0.1
```
