### ISSUE TITLE
Rasa integration not working for rasa > 2.0

### ISSUE THREAD

**Issue by pfjason** [rhasspy/rhasspy#271]
The documentation specifies pulling rasa/rasa:latest-spacy-en which right now pulls a 3.0 version which does not work the way the configuration specifies as of 2.0 according to this [similar question](https://forum.rasa.com/t/trainin-error-with-yaml-validation-error/42690/3) in the rasa forums for a user using the `pipeline: pretrained_embeddings_spacy` rasa configuration. The solution in that question advises checking the pipeline doc [here](https://rasa.com/docs/rasa/tuning-your-model/#how-to-choose-a-pipeline). 

Additionally, according to this doc it looks like the intent_examples.md generation will need to be updated to use the format specified in  as below, as once I updated my rasa config in Rhasspy to use the new config format I'm getting training errors due to bad example formatting. There's also a small issue with the docker run command in the documentation which specifies the comand parameter as `--enable-api`, but in newer rasa docker images you would need to do `run --enable-api`

I've currently taken the lazy way out and changed 'rasa/rasa:latest-spacy-en' in my docker-compose to 'rasa/rasa:1.10.26-spacy-en'. As far as I can tell this is the last 1.0 version available. 

``` YAML
nlu:
- intent: check_balances
  examples: |
    - How much money do I have?
    - what's my account balance?

- intent: transfer_money
  examples: |
    - I want to transfer money to my savings account
    - transfer money
```
