### ISSUE TITLE
How to make the bluetooth headset work in Rhasspy Assistant?

### ISSUE THREAD

**Issue by DivanX10** [rhasspy/rhasspy#323]
I need your help. Please help me make the bluetooth headset work in the Rhasspy Assistant addon. I tried different options and i never managed to get the bluetooth headset in Chess Assistant to work. Although the bluetooth headset works fine in Debian 11.6, you can activate the HSP/HFP profile and both the microphone and audio playback in the speaker will work. [Here i detail everything расписал](http://community.home-assistant.io/t/how-to-transfer-a-bluetooth-headset-microphone-from-debian-11-to-home-assistant-rhasspy-assistant/543630) what I did and how. The only solution i came up with was to buy a radio microphone and connect it to the 3.5 mini jack connector, and i took the Mi Portable Bluetooth Speaker BHR4802GL to output the sound. But this is not what i would like to have, but i would like a Bluetooth wireless speaker with a microphone to be able to fully work in the Rhasspy Assistant addon

Here's what it looks like

The microphone radio itself
![image](https://user-images.githubusercontent.com/64090632/224567043-fcdb0d7a-3c87-45ac-a273-95becc483c65.png)

Radio Microphone and Mi Portable Bluetooth Speaker BHR4802GL
![image](https://user-images.githubusercontent.com/64090632/224567067-c2b8a10d-1ca5-4c2f-a8c7-a6747128433d.png)

In the addon settings, Rhasspy Assistant specified a built-in sound card for the microphone, and for Bluetooth Speaker specified Mi Portable Bluetooth Speaker
![image](https://user-images.githubusercontent.com/64090632/224567133-dfd8bbf0-9d05-4bb8-a920-8638a7c212af.png)

I couldn't get it to work through docker by using this option. I took an example from [here](https://github.com/rhasspy/rhasspy/pull/215/commits/7a16d4cbfee9f0c47779234a04f2bdb210a5daec )

```
version: "3.8"
services:
  rhasspy:
    image: rhasspy/rhasspy
    container_name: rhasspy
    privileged: true
    network_mode: bridge
    restart: unless-stopped #always
    ports:
      - 12101:12101 #http
      - 12183:12183 #mqtt
    devices:
      - /dev/snd/*
    volumes:
      - /home/docker/rhasspy/profiles:/profiles
      - /etc/localtime:/etc/localtime:ro
      - /home/docker/rhasspy/.config/pulse/cookie:/home/rhasspy/.config/pulse/cookie
      - /run/user/1000/pulse:/run/user/1000/pulse
      - /home/docker/rhasspy/pulseaudio:/etc/pulse/client.conf.d
    command: --user-profiles /profiles --profile ru
    environment:
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
      - PULSE_RUNTIME_PATH=/run/user/1000/pulse
```
