### ISSUE TITLE
rhasspy-snips-nlu-hermes missing in 2.5.0 image

### ISSUE THREAD

**Issue by chrisbloecker** [rhasspy/rhasspy#76]
I tried using Snips NLU for intent recognition but training didn't terminate and in the log I found

```
INFO spawnerr: can't find command 'rhasspy-snips-nlu-hermes'
```

I think this is because `rhasspy-snips-nlu` and `rhasspy-snips-nlu-hermes` are missing in the `Dockerfile`. I tried adding them to build the image myself, but didn't quite figure out how to build it with the multi arch targets and so on...

**Comment by chrisbloecker** [comment]
So as a quick fix it seems to work to run the image, mount `rhasspy-snips-nlu` and `rhasspy-snips-nlu-hermes` into it and install it from there...

In case someone else runs into this problem, what I did was (and I'm sure some things can be done shorter):
```bash
git clone https://github.com/rhasspy/rhasspy.git
git submodule init
git submodule update
```

Then, for simplicity, I mounted the whole repo into the container (with docker-compose, and of course, adjust your path...)
```yaml
rhasspy:
    image: "rhasspy/rhasspy:2.5.0"
    restart: unless-stopped
    volumes:
        - "./profiles:/profiles"
        - "/home/chris/git/rhasspy:/rhasspy"
    ports:
        - "12101:12101"
    command: --user-profiles /profiles --profile en
```

Start an interactive shell in the container
```bash
docker exec -ti <rhasspy_container_id> /bin/bash
```

In the container, activate the virtual environment and install `rhasspy-snips-nlu` and `rhasspy-snips-nlu-hermes`
```bash
source /usr/lib/rhasspy/bin/activate
pip install /rhasspy/rhasspy-snips-nlu/
pip install /rhasspy/rhasspy-snips-nlu-hermes/
```

The auto download of the files that snips nlu needs didn't work for me, so I downloaded it manually
```bash
python -m snips_nlu download en
```

And last, to make it persistent, create a new image from the container to use in the future
```bash
docker commit <rhasspy_container_id> rhasspy:2.5.0-with-snips-nlu
```

Now the downloaded files for snips nlu are also persisted in the image, which is of course not desirable, but this is only a dirty hack anyway...

But I'm still left with one problem: whenever I train snips nlu, I need to remove the engine directory manually (or figure out in which file I have to adjust something to automate that...) because I get
```python
TrainingFailedException: Path already exists: /profiles/en/snips/engine
```

Well, I hope there's someone who finds this useful...
Cheers!
